version: "3"
services:

  backend:
    build: ${PWD-.}/backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD-.}/backend:/code
    ports:
      - "8000:8000"

  frontend:
    build: ${PWD-.}/frontend
    volumes:
      - ${PWD-.}/frontend/dist/:/usr/share/nginx/html
    environment:
      NODE_ENV: "development"
    ports:
      - "8085:80"
    depends_on:
      - backend
